CREATE TABLE IF NOT EXISTS users 
(
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(50),
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash TEXT(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_login TIMESTAMPTZ,
)